apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app-deployment
  labels:
    environment: test
spec:
  replicas: 2
  selector: 
    matchLabels:
      environment: test
  template:
    metadata: 
      # name: php-app
      labels:
        environment: test
    spec:
      containers:
      - name: php-app
        # image: "docker.io/keneojiteli/php-app"
        image: keneojiteli/php-app
        env:
            - name: DB_HOST
              value: 10.1.0.18 # IP of my statefulset

            - name: MYSQL_PORT
              value: "3306"

            - name: MYSQL_USER
              value: kene1
              
            - name: MYSQL_PASSWORD
              valueFrom: 
               secretKeyRef: 
                key: MYSQL_PASSWORD
                name: mysql-secret

            - name: MYSQL_DATABASE
              value: feedback
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"        
        ports: 
        - containerPort: 80



# Error: One or more containers do not have resource limits - this could starve other processes