apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    deimos.io/environment-local: deploy
  name: mysql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kene-cicd-project
  source:
    # chart: mysql
    # repoURL: https://charts.bitnami.com/bitnami 
    # targetRevision: HEAD
    repoURL: https://github.com/DeimosCloud/kene-cicd.git
    path: src/mysql
    targetRevision: HEAD
    helm:
      releaseName: mysql
      values: |
        fullnameOverride: mysql
        livenessProbe: 
          enabled: false
        readinessProbe: 
          enabled: false
        startupProbe:
          enabled: false
        auth: 
          existingSecret: mysql-secret
        service:
          port: 3306
        db:
          name: my_database
          
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1




