apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  deimos.io/application: myapp
  deimos.io/customer: deimos.io
  deimos.io/owner: sre@deimos.io
  deimos.io/project: myapp
  deimos.io/version: 0.0.1
  deimos.io/repo: https://gitlab.com/deimosdev/tooling/myapp.git
resources: 
  - deimos.io
  # - podtato-head.yaml
  - loadgenerator.yaml
  - node-web-app.yaml
  - rabbitmq-cluster-operator.yaml
  - tekton.yaml
  - deploy-mysql.yaml
  - grafana-agent.yaml
  - mysql-exporter.yaml
  - elasticsearch.yaml
  # - kibana.yaml
  # - sql-test.yaml
  
