---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-cluster-operator
  namespace: argocd
  annotations:
    deimos.io/environment-local: deploy
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # project: myapp-project
  project: kene-cicd-project
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 3.4.1
    chart: rabbitmq-cluster-operator
    helm:
      releaseName: rabbitmq-cluster-operator
      values: |
        rabbitmqImage:
          tag: 3.9.29-debian-11-r22
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1
