apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
spec:
  containers:
  - name: mysql-container
    image: alpine
    command: ['sh','-c', "sleep 1800m"]
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 512Mi
        cpu: "1"
      # requests:
      #   memory: 256Mi
      #   cpu: "0.2" 